### ISSUE TITLE
CSRF Token invalid when using PostForm

### ISSUE THREAD

**Issue by FireDrunk** [joernott/go-proxmox#8]
I've been trying to implement your lib with a simple CLI. When using the PostForm function, I'm getting a CSRFToken validation error. Listing stuff works fine.

Implementation: https://github.com/FireDrunk/go-proxmox-cli/blob/master/main.go

Output:
```
Connected to: https://10.0.2.15:8006
Error while posting form
HTTP Error 401 403 Permission check failed (Permission denied - invalid csrf token)
```

**Comment by joernott** [comment]
Lines 81-98 in https://github.com/joernott/go-proxmox/blob/master/proxmox.go are supposed to take care of that. I currently have no test instance available and very limited spare time, so I can't debug/test your code right now.

What proxmox version are you running? Maybe the ticket handling changed since I developed this on version 3.

**Comment by FireDrunk** [comment]
This fixed it:
https://github.com/FireDrunk/go-proxmox/commit/8aec9e7d3e5674e7e8730afc0c459c6ab204b797#diff-62c2f0149278846e2dbc849946648586R86

**Comment by joernott** [comment]
Thank you, I have merged that fix back to master.
